# Generated by Django 4.2.1 on 2023-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_player_name_match_away_team_odds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='college',
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
