# Generated by Django 4.2.1 on 2023-05-29 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_player_college_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=None, null=True)),
                ('home_team_odds', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('away_team_odds', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='games.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='games.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
