# Generated by Django 4.2.1 on 2023-05-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
