# Generated by Django 4.2.1 on 2023-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_datetime_end_alter_game_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='commentary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='weather',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
