# Generated by Django 4.2.1 on 2023-06-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
