# Generated by Django 4.2.1 on 2023-06-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_userprofile_selected_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
